### ISSUE TITLE
Get rid of Sosh content

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ouds-ios#180]
### Description

This repository includes references to a Sosh theme, along with specific files and documentation. However, all references to Sosh should be removed, as they will be managed in a separate private repository.

If you prefer not to remove everything because it could be useful for testing, you can simply rename the theme to something like "Fake" or any placeholder of your choice, and change the color values too.

**Comment by pylapp** [comment]
@julien-deramond  So we should alos get rid of Orange Theme with brand colors?

**Comment by pylapp** [comment]
No _Fake_ theme will be added in the _OUDS_ library, it is a non-sens because it will be only for test purposes, but some fake theme can be added in the app insteaed using the library. However, we won't implement that until we have the needs or if issues have been created or requirements defined by stakeholders.

**Comment by pylapp** [comment]
ℹ️ Released with version [v0.4.0](https://github.com/Orange-OpenSource/ouds-ios/releases/tag/0.4.0) 🚀
